/******************************************************************************
*
*  				Copyright (C), 2023-2050, jyc Tech. Co., Ltd.
*
* File Name     : customer_config.h
* Description   : Used to select customer configuration
*  
* History       :
* Version   Date         Author    Description
* 0.01      2023-08-16   jyc.rd    Create this file.
*
******************************************************************************/

#ifndef __CUSTOMER_CONFIG_H__
#define __CUSTOMER_CONFIG_H__

/* Includes ------------------------------------------------------------------*/
#include "customer_device_type.h"

//�ͻ�����:customer + name + hmi + current
#define CUSTOMER_DEFAULT_NONE_16A									0
#define CUSTOMER_DEFAULT_NONE_13A									1
#define CHENGGONG_JYC_GD_A01_NONE_16A_KEYPAD						2
#define NENGSHENG_K046_23110007_JYC_GD_A02_NONE_16A_KEYPAD			3
#define CUSTOMER_JYC_GB_A01_FC01_ONEKEY_16A							4
#define CUSTOMER_JYC_GB_A10L_NONE_NONE_32A							5
#define JYC_K046_24030002_JYC_GB_A10L_MS523_BL0939_32A				6
#define CUSTOMER_DEFAULT_NONE_16A_HMI_TJC3224T128 7



#define CUSTOMER_ERROR												0xFFFF

//�ͻ�ѡ��
#define CUSTOMER_SELECT						CUSTOMER_JYC_GB_A01_FC01_ONEKEY_16A//JYC_K046_24030002_JYC_GB_A10L_MS523_BL0939_32A

#ifndef CUSTOMER_SELECT
	#define CUSTOMER_SELECT					CUSTOMER_ERROR
#endif

#if(CUSTOMER_SELECT == CUSTOMER_DEFAULT_NONE_16A)
    #define CUSTOMER_BOARD_SELECT					JYC_GD_A01
	#define CUSTOMER_HMI_SELECT						CUSTOMER_HMI_TYPE_NONE
	#define CUSTOMER_MAX_CURRENT_SELECT				CUSTOMER_MAX_CURRENT_TYPE_16A
	#define LOG_LEVEL								LOG_LEVEL_DEBUG
#elif(CUSTOMER_SELECT == CUSTOMER_DEFAULT_NONE_13A)
    #define CUSTOMER_BOARD_SELECT					JYC_GD_A01
	#define CUSTOMER_HMI_SELECT						CUSTOMER_HMI_TYPE_NONE
	#define CUSTOMER_MAX_CURRENT_SELECT				CUSTOMER_MAX_CURRENT_TYPE_13A
	#define LOG_LEVEL								LOG_LEVEL_DEBUG
#elif(CUSTOMER_SELECT == CHENGGONG_JYC_GD_A01_NONE_16A_KEYPAD)
    #define CUSTOMER_BOARD_SELECT					JYC_GD_A02
	#define CUSTOMER_CHARGE_STANDARD_SELECT			CUSTOMER_CHARGE_STANDARD_OB
	#define CUSTOMER_HMI_SELECT						CUSTOMER_HMI_TYPE_NONE
	#define CUSTOMER_MAX_CURRENT_SELECT				CUSTOMER_MAX_CURRENT_TYPE_16A
	#define CUSTOMER_LED_SELECT						LED_TYPE_CHENGGONG
	#define LOG_LEVEL								LOG_LEVEL_DEBUG
#elif(CUSTOMER_SELECT == NENGSHENG_K046_23110007_JYC_GD_A02_NONE_16A_KEYPAD)
    #define CUSTOMER_BOARD_SELECT					JYC_GD_A02
	#define CUSTOMER_CHARGE_STANDARD_SELECT			CUSTOMER_CHARGE_STANDARD_OB
	#define CUSTOMER_HMI_SELECT						CUSTOMER_HMI_TYPE_NONE
	#define CUSTOMER_MAX_CURRENT_SELECT				CUSTOMER_MAX_CURRENT_TYPE_16A
	#define CUSTOMER_LED_SELECT						LED_TYPE_DEFUAL
	#define LOG_LEVEL								LOG_LEVEL_DEBUG
	
#elif(CUSTOMER_SELECT == CUSTOMER_JYC_GB_A01_FC01_ONEKEY_16A)
    #define CUSTOMER_BOARD_SELECT					JYC_GD_A02
    #define CUSTOMER_CHARGE_STANDARD_SELECT 		CUSTOMER_CHARGE_STANDARD_OB
    #define CUSTOMER_HMI_SELECT 					CUSTOMER_HMI_TYPE_NONE
    #define CUSTOMER_MAX_CURRENT_SELECT 			CUSTOMER_MAX_CURRENT_TYPE_16A
    #define LOG_LEVEL								LOG_LEVEL_DEBUG
#elif(CUSTOMER_SELECT == CUSTOMER_JYC_GB_A10L_NONE_NONE_32A)
    #define CUSTOMER_BOARD_SELECT					JYC_GD_A10L
	#define CUSTOMER_HMI_SELECT						CUSTOMER_HMI_TYPE_NONE
	#define CUSTOMER_CARD_SELECT					CUSTOMER_CARD_TYPE_MS523
	#define CUSTOMER_CARD_UART_SELECT				CUSTOMER_UART_TYPE_0
	#define CUSTOMER_MAX_CURRENT_SELECT				CUSTOMER_MAX_CURRENT_TYPE_32A
	#define LOG_LEVEL								LOG_LEVEL_DEBUG
	#define CUSTOMER_CARD_KEY_SELECT				CUSTOMER_CARD_KEY_UNIQUE
#elif(CUSTOMER_SELECT == JYC_K046_24030002_JYC_GB_A10L_MS523_BL0939_32A)
    #define CUSTOMER_BOARD_SELECT					JYC_GD_A10L
	#define CUSTOMER_HMI_SELECT						CUSTOMER_HMI_TYPE_NONE
	#define CUSTOMER_CARD_SELECT					CUSTOMER_CARD_TYPE_MS523
	#define CUSTOMER_CARD_UART_SELECT				CUSTOMER_UART_TYPE_0
	#define CUSTOMER_MAX_CURRENT_SELECT				CUSTOMER_MAX_CURRENT_TYPE_32A
	#define LOG_LEVEL								LOG_LEVEL_DEBUG
	#define CUSTOMER_CARD_KEY_SELECT				CUSTOMER_CARD_KEY_UNIQUE

#elif(CUSTOMER_SELECT == CUSTOMER_DEFAULT_NONE_16A_HMI_TJC3224T128)
    #define CUSTOMER_BOARD_SELECT					JYC_GD_A02
	#define DATA_COUNTING_MODE_SELECT    			CHARGING_DATA_ACCUMULATION
	#define CUSTOMER_HMI_SELECT						CUSTOMER_HMI_TYPE_TJC3224T128
	#define CUSTOMER_MAX_CURRENT_SELECT				CUSTOMER_MAX_CURRENT_TYPE_16A
	#define LOG_LEVEL								LOG_LEVEL_DEBUG
#else
	#error
#endif


//Ĭ������
#ifndef CUSTOMER_HMI_SELECT
	#define CUSTOMER_HMI_SELECT						CUSTOMER_HMI_TYPE_NONE
#endif

#ifndef CUSTOMER_MAX_CURRENT_SELECT
	#define CUSTOMER_MAX_CURRENT_SELECT				CUSTOMER_MAX_CURRENT_TYPE_16A
#endif

#ifndef LOG_LEVEL
	#define LOG_LEVEL								LOG_LEVEL_NULL
#endif

#ifndef CUSTOMER_LED_SELECT
	#define CUSTOMER_LED_SELECT								LED_TYPE_DEFUAL
#endif

#ifndef CUSTOMER_BOARD_SELECT
	#define CUSTOMER_BOARD_SELECT					JYC_GD_A01
#endif


#ifndef CUSTOMER_CHARGE_STANDARD_SELECT
	#define CUSTOMER_CHARGE_STANDARD_SELECT			CUSTOMER_CHARGE_STANDARD_GB
#endif


#ifndef CUSTOMER_CARD_SELECT
	#define CUSTOMER_CARD_SELECT					CUSTOMER_CARD_TYPE_NONE
#endif


//����Կѡ��,Ĭ��ͨ����Կ
#ifndef CUSTOMER_CARD_KEY_SELECT
	#define CUSTOMER_CARD_KEY_SELECT				CUSTOMER_CARD_KEY_COMMON
#endif


//����������ѡ��
#ifndef CUSTOMER_CARD_UART_SELECT
	#define CUSTOMER_CARD_UART_SELECT				CUSTOMER_UART_TYPE_NONE
#endif


//�������ˢ��ѡ��
#ifndef DATA_COUNTING_MODE_SELECT
	#define DATA_COUNTING_MODE_SELECT				CHARGING_DATA_DOES_NOT_ACCUMULATION
#endif



#endif

